language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - cargo install --force cargo-audit
script:
  - cargo build --verbose
  - cargo build --examples
  - cargo test --verbose
  - cargo audit
